### PR TITLE
Punch hole in firewalld

### PR DESCRIPTION
**Pull request by sireliah**
This is a change that makes Dragit automatically detect if firewalld is going to prevent the application from listening on required ports. For more info, please check #9

### CODE REVIEW

**Comment by sp1ritCS** [comment]
If you want to save it permanently I think you should do so over a firewall rule, not just by adding the port to the list of open ports, as a user checking firewall-config later on will have no idea why the port is there.

**Comment by sireliah** [comment]
> If you want to save it permanently I think you should do so over a firewall rule, not just by adding the port to the list of open ports, as a user checking firewall-config later on will have no idea why the port is there.

Do you mean the `addRule` from [direct config](https://firewalld.org/documentation/man-pages/firewalld.dbus.html#FirewallD1.config.direct) or a rich rule? None of them have any comment section and direct rules are hidden by default in firewall-config, so it might not be much better. Or you meant something different?

I also thought about the zone, but zone is not in use unless you attach it to a connection or make a default zone, which creates all sorts of problems.

**Comment by sp1ritCS** [comment]
Yeah, my bad. I was talking about "services" (the files in `/usr/lib/firewalld/services/*.xml`)

**Comment by sireliah** [comment]
firewall_prompt

@sp1ritCS Now there is separate "dragit" service with description. Please take a look if you like.

**Comment by sp1ritCS** [comment]
Great!

looks good from my side 👍🏻

**Pull request merged**
